### ISSUE TITLE
The TeaBot should CONGRATULATE the paper author

### ISSUE THREAD

**Issue by drphilmarshall** [yymao/kipac-teabot#13]
eg:

Here's a list of new arXiv papers authored by KIPAC members:

    Eli Rykoff: [1501.02840] Environment-based selection effects of Planck clusters

Many congratulations, Eli! 

This message is automatically generated and sent by KIPAC TeaBot.
Create an issue if you have any suggestions/questions.

**Comment by yymao** [comment]
Agreed. However we should consider:
1. Should we send this kind of emails to everyone or only to TeaBot subscribers? 
2. Name mismatching is still possible. For KIPAC blog it doesn't matter because someone would be screening this. An automated false congratulation email, on the other hand, could be a bit embarrassing.

**Comment by drphilmarshall** [comment]
Hah! Yes, that's true. Maybe for now the teabot should just remind the
email reader to congratulate the author :-)

"If this report is accurate, you might send Eli <rykoff@slac.stanford.edu>
a congratulatory email! :-)"

**Comment by yymao** [comment]
This sounds a OK workaround. In the case of multiple papers/authors are found, should TeaBot just lists all emails or send separate emails for each paper/author so you can just forward it?

**Comment by drphilmarshall** [comment]
I guess having the teabot cc the authors might make congratulations easy!

**Comment by yymao** [comment]
But cc'ing the authors would cause the same issues as automatically sending
congratulations would, as we discussed above.

**Comment by drphilmarshall** [comment]
Good point. I'd say one paper per email, and keep it simple. This also has
the nice property that everyone's achievement is treated equally :-)

**Comment by mssgill** [comment]
Yes, i'd agree with above - 1 email per paper, list all the Kipac authors' e-addresses in it.  

I often tell people in person when i notice, so this will make it even more 'complete' for me to be able to do so (since it's only a subset that ever actually get discussed at Teas), and it will raise up the issue for all Kipac folk too when someone posts up a paper, making the whole dept more "collegial", i feel.

**Comment by yymao** [comment]
This feature has been implemented in 82f37132. 

TeaBot only sends one email per day, but would include members' emails in a format that is easy (i.e. can be copy-pasted) for the discovery team to send a congratulatory email.
