### ISSUE TITLE
teabot sorting of full day's paper lists

### ISSUE THREAD

**Issue by rhw** [yymao/kipac-teabot#15]
How about a link at the bottom of the teabot mail, that gives the full day's arxiv postings sorted by teabot relevance to me?

**Comment by yymao** [comment]
A full list (up to 50 papers) sorted by relevance will be included in the email if the user requests: a0fa3220

At this moment it is still not possible to have this list on a website for the user to visit (because the TeaBot did not store the information about arxiv papers once the emails were sent).
